src/api/api.js
src/pages/Home.jsx

- api 연결
- 2024/07/22
- Home.jsx파일에 useEffect로 최초 실행시 콘솔에 출력
- api.js 파일 추가

TEST: api 연결 확인 중

---

src/App.css
src/index.css
src/pages/MakeTimetable/MakeT.jsx
src/pages/Nav.jsx
src/pages/home/HomeBottom.jsx
src/pages/home/HomeMiddle1.jsx
src/pages/home/HomeMiddle2.jsx
src/pages/home/HomeTop.jsx

- [1440px로 변경된 디자인 따라 홈화면 수정하엿습니다
- 2024/07/27
- 디자인 전체 크기 변경
- 화이팅
X

디자인 사이즈 수정

---

package.json

FIX: 배포위한 package.json 파일 수정

---

src/api/api_login.js

CHORE: 카카오로그인 테스트

---

src/api/api_login.js

FIX: 로그인 위해 경로변경

---

src/api/api_dailyTimeTable.js
src/component_TimeTable/ForTimeTable/OneDayTimeTable.jsx
src/component_TimeTable/ForTimeTable/TimeEditOn.jsx
src/component_TimeTable/ForTimeTable/TimeTableCom.jsx
src/component_TimeTable/ForTimeTable/TimeTableContainer.jsx
src/component_TimeTable/ForTimeTable/TimeTableEach.jsx
src/component_TimeTable/RetrospectCom.jsx

FEAT: api 연결중

---

src/pages/MakeTimetable/MakeT.jsx

feat : 네비게이트 올테스크

---

src/App.js
src/assets/img/day2.svg
src/component_PastWorkation/HistoryAllCom.jsx
src/component_PastWorkation/OneWorkation.jsx
src/pages/PastWorkation/OnePast.jsx

feat: 지난워케이션 목록

---

src/App.js
src/component_PastWorkation/HistoryAllCom.jsx
src/component_PastWorkation/OneCom/OnePast.jsx
src/component_PastWorkation/OneWorkation.jsx
src/component_ThisAllWorkation/ThisAllCom.jsx
src/pages/PastWorkation/OnePast.jsx

feat: 지난워케이션 연결

---

src/component_PastWorkation/OneCom/OnePast.jsx
src/component_PastWorkation/OneWorkation.jsx
src/component_ThisAllWorkation/InnerOneTable.jsx
src/component_ThisAllWorkation/ThisAllBottom.jsx
src/component_ThisAllWorkation/ThisAllCom.jsx
src/component_ThisAllWorkation/ThisAllGraph.jsx
src/component_ThisAllWorkation/ThisAllMiddle.jsx
src/component_ThisAllWorkation/ThisAllRetro.jsx
src/component_ThisAllWorkation/ThisAllTodo.jsx
src/pages/MakeTimetable/MakeT.jsx
src/pages/PastWorkation/HistoryAll.jsx
src/pages/PastWorkation/HistoryEach.jsx
src/pages/ThisAllWorkation/AllTask.jsx
src/recoil/makeTAtom.js

feat: 전체일정 투두,회고,그래프 추가 및 지난회고경로수정

---

src/api/api_dailyTimeTable.js
src/api/mappingData.js
src/component_TimeTable/ForTimeTable/OneDayTimeTable.jsx
src/component_TimeTable/ForTimeTable/TimeEditOn.jsx
src/component_TimeTable/ForTimeTable/TimeTableCom.jsx
src/component_TimeTable/ForTimeTable/TimeTableContainer.jsx
src/component_TimeTable/ForTimeTable/TimeTableEach.jsx
src/component_TimeTable/TodoListCom.jsx
src/pages/TimeTable/TimeTable.jsx

오늘자 전체 투두 불러오기 구현

---

src/api/api_dailyTimeTable.js
src/component_Location/Card.jsx
src/component_TimeTable/ForTimeTable/OneDayTimeTable.jsx
src/component_TimeTable/ForTimeTable/TimeTableCom.jsx
src/component_TimeTable/ForTimeTable/TimeTableContainer.jsx
src/component_TimeTable/ForTimeTable/TimeTableEach.jsx
src/component_TimeTable/TodoListCom.jsx

시간표 버그 수정 및 투두 조회

---

src/api/api_dailyTimeTable.js
src/assets/img/오늘일정/schedule/장소.svg
src/component_Location/Card.jsx
src/component_Location/Location.jsx
src/component_Location/RestLoca.jsx
src/component_Location/WorkLoca.jsx
src/component_TimeTable/ForTimeTable/OneDayTimeTable.jsx
src/component_TimeTable/ForTimeTable/TimeTableEach.jsx
src/component_TimeTable/TodoListCom.jsx
src/pages/TimeTable/TimeTable.jsx

FEAT: 카카오주소연결

---

src/component_ThisAllWorkation/InnerOneTable.jsx
src/component_ThisAllWorkation/InnerOneTimeTable.jsx
src/component_ThisAllWorkation/ThisAllRetro.jsx
src/component_ThisAllWorkation/ThisAllTodo.jsx
src/pages/MakeTimetable/MakeT.jsx

Feat/past : 전체일정, 지난 일정에 시간표 get으로 색칠

---

src/component/AutoComplete.jsx
src/component/MyPageModal.jsx
src/pages/MakeTimetable/MakeT.jsx

FIX: 워케이션등록 에러처리

---

src/api/api_PastTimeTable.js
src/api/api_ThisAllTimeTable.js
src/component/MyPageModal.jsx
src/component_PastWorkation/HistoryAllCom.jsx
src/component_PastWorkation/OneWorkation.jsx
src/component_ThisAllWorkation/ThisAllComReal.jsx
src/pages/ThisAllWorkation/AllTask.jsx

FEAT: 전체일정 api 연결

---

src/api/api_dailyTimeTable.js
src/component_ThisAllWorkation/ThisAllBottomReal.jsx
src/component_ThisAllWorkation/ThisAllComReal.jsx
src/pages/MakeTimetable/MakeT.jsx

FEAT: 전체일정 edit버튼 추가-동작은 아직 미구현

---

src/App.js
src/api/api_ThisAllTimeTable.js
src/api/api_alert.js
src/api/api_dailyTimeTable.js
src/component/AlertModal.jsx
src/component_ThisAllWorkation/ThisAllBottomReal.jsx
src/component_ThisAllWorkation/ThisAllComReal.jsx
src/component_TimeTable/ForTimeTable/OneDayTimeTable.jsx
src/component_TimeTable/TodoListCom.jsx
src/pages/ThisAllWorkation/ThisAllWorkationToTimeTable.jsx
src/recoil/alertAtom.js

FEAT: 투두수정 및 타이머 구현

---

src/component_ThisAllWorkation/ThisAllBottomReal.jsx

FIX:CSS 수정

---

src/api/api_login.js

FIX: 배포주소로 수정

---

src/App.js
src/api/api_dailyTimeTable.js
src/api/api_location.js
src/component_Location/Location.jsx
src/component_Location/RestLoca.jsx
src/component_Location/WorkLoca.jsx
src/component_ThisAllWorkation/ThisAllGraph.jsx
src/component_ThisAllWorkation/ThisAllTodo.jsx
src/component_TimeTable/ForTimeTable/OneDayTimeTable.jsx
src/component_TimeTable/GraphCom.jsx
src/component_TimeTable/TodoListCom.jsx
src/pages/ThisAllWorkation/ThisAllWorkationToTimeTable.jsx
src/pages/TimeTable/TimeTable.jsx

FIX: 기타 버그 잡는 중

---

src/component_TimeTable/TodoListCom.jsx
src/pages/MakeTimetable/MakeT.jsx

FIX: 에러잡기 끝

---

src/api/api_dailyTimeTable.js
src/component_ThisAllWorkation/ThisAllBottom.jsx
src/pages/TimeTable/TimeTable.jsx

feat: 일일일정 404 캐치

---

src/component_PastWorkation/HistoryAllCom.jsx

FEAT: 모든 워케이션 없는 경우 페이지 추가

---

public/index.html
src/component_TimeTable/ForTimeTable/TimeEditOn.jsx
src/component_TimeTable/TodoListCom.jsx
src/pages/Home.jsx
src/pages/MakeTimetable/Loading.jsx
src/pages/MakeTimetable/MakeT.jsx
src/pages/Nav.jsx
src/pages/TimeTable/TimeTable.jsx

FIX: css수정

---

src/component_Location/Card.jsx
src/component_Location/Location.jsx
src/pages/MakeTimetable/Loading.jsx
src/pages/Nav.jsx

feat: 네브바 및 여러개 css수정

---

src/api/api_dailyTimeTable.js
src/component_ThisAllWorkation/InnerOneTimeTable.jsx
src/component_TimeTable/ForTimeTable/TimeTableEach.jsx

FIX: timetable 24시 에러 해결

---

src/Workation/DailyWorkation/DailyTodoList.jsx
src/Workation/EachWorkation/OneWorkation.jsx
src/Workation/EachWorkation/OneWorkationDetail.jsx
src/Workation/EachWorkation/OneWorkationPast.jsx
src/Workation/EachWorkation/OneWorkationRetrospect.jsx
src/Workation/EachWorkation/OneWorkationTextBox.jsx
src/Workation/EachWorkation/OneWorkationTimeTable.jsx
src/Workation/EachWorkation/OneWorkationTimeTableEach.jsx
src/Workation/EachWorkation/OneWorkationTimeTableList.jsx
src/Workation/EachWorkation/OneWorkationTodo.jsx
src/Workation/PastWorkation/OnePastWorkationList.jsx
src/Workation/PastWorkation/PastWorkation.jsx
src/Workation/PastWorkation/PastWorkationList.jsx
src/Workation/TimeTable/TimeEditOn.jsx
src/Workation/TimeTable/TimeTable.jsx
src/api/api_ThisAllTimeTable.js
src/api/api_Workation.js

REFACTOR: 시간표 최적화
